services:
  occupi-web-prod:
    image: $DOCKER_USERNAME/occupi-web:latest
    container_name: occupi-web-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:4000"
    networks:
      - webnet
    volumes:
      - /etc/letsencrypt/live/occupi.tech/fullchain.pem:/etc/letsencrypt/live/occupi.tech/fullchain.pem:ro
      - /etc/letsencrypt/live/occupi.tech/privkey.pem:/etc/letsencrypt/live/occupi.tech/privkey.pem:ro

networks:
  webnet:
    external: true