services:
  occupi-web-prod:
    image: $DOCKER_USERNAME/occupi-web:latest
    container_name: occupi-web-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "4000:5173"
    networks:
      - webnet
    volumes:
      - /etc/letsencrypt/live/app.occupi.tech/fullchain.pem:/etc/letsencrypt/live/app.occupi.tech/fullchain.pem:ro
      - /etc/letsencrypt/live/app.occupi.tech/privkey.pem:/etc/letsencrypt/live/app.occupi.tech/privkey.pem:ro
    restart: on-failure:5

networks:
  webnet:
    external: true