# Use the official bun image as a base
FROM oven/bun:latest

# Install dependencies required by the canvas package
RUN apt-get update && apt-get install -y \
    libcairo2-dev \
    libjpeg-dev \
    libpango1.0-dev \
    libgif-dev \
    build-essential \
    g++

# Set the current working directory inside the container
WORKDIR /app

# copy bun.lockb package.json 
COPY bun.lockb package.json ./

# install dependencies
RUN bun install

# copy the source code into the container
COPY . .

# Build the next.js application
RUN bun run build

# Expose the port the app runs on
EXPOSE 4001

# Command to run the executable
CMD ["bun", "preview"]
