services:
  occupi-web-dev:
    image: occupi-web:latest-develop
    container_name: occupi-web-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "4001:5173"
    restart: on-failure:5