services:
  occupi:
    image: $DOCKER_USERNAME/occupi:latest
    container_name: occupi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:3000"
    networks:
      - webnet
    restart: on-failure:5

networks:
  webnet:
    external: true