import { server } from '@passwordless-id/webauthn' 

const expected = {
    challenge: "a7c61ef9-dc23-4806-b486-2428938a547e", // whatever was randomly generated by the server
    origin: "http://localhost:5173",
}
const registration: any = undefined; // declare the 'registration' variable
const registrationParsed = await server.verifyRegistration(registration, expected)