export const pages = [
    { id: 1, path: "/", title: "Dashboard Overview", description: "View the overview of the system info at a glance" },
    { id: 2, path: "/employees", title: "Dashboard Employees", description: "View employee details" },
    { id: 4, path: "/ai-dashboard", title: "AI Dashboard", description: "Leverage the power of AI to analyze office trends (office occupancy, available desks, reservations, check-ins today)" },
    { id: 5, path: "/rooms", title: "Rooms", description: "Update and edit available rooms in the building" },
    { id: 6, path: "/reports", title: "Reports", description: "Generate and download reports for analysis" },
    { id: 7, path: "/faq", title: "FAQ", description: "Get help on app usage" },
    { id: 8, path: "/settings/profile", title: "Profile", description: "Update your profile information" },
    { id: 9, path: "/settings/appearance", title: "Appearance", description: "Change the appearance of the app" },
    { id: 10, path: "/settings/notifications", title: "Notifications", description: "Manage your notification settings" },
    { id: 11, path: "/settings/security", title: "Security", description: "Manage your security settings" },
    { id: 12, path: "/settings/about", title: "About, Privacy Policy, TOS, User Manual", description: "View information about the app" },
    { id: 13, path: "/booking-statistics", title: "Booking Statistics", description: "View statistics on bookings" },
    { id: 14, path: "/worker-dashboard", title: "Worker Dashboard", description: "View organisation wide worker statistics" },
    { id: 15, path: "/employees", title: "Employees", description: "View employee details and employee statistics on an individualised level" },
    { id: 16, path: "/booking-statistics/overview", title: "Bookings Overview", description: "View overview statistics on bookings" },
    { id: 17, path: "/booking-statistics/bookings-dashboard", title: "Bookings Dashboard", description: "View deeper statistics on bookings" },
    { id: 18, path: "/user-locations", title: "User login locations", description: "Manage users allowed login locations, see their ip addresses for these allowed locations"},
    { id: 19, path: "/", title: "At a glance", description: "View the overview of the system info at a glance" },
    { id: 20, path: "/employees", title: "Admin", description: "Change admin status of employees" },
    { id: 21, path: "/employees", title: "Employee Statistics", description: "View employee statistics" },
    { id: 22, path: "/employees", title: "Site status", description: "View employee on site and offsite status" },
    { id: 23, path: "/employees", title: "Mail employee", description: "Send a personalised email to your employee" },
    { id: 24, path: "/employees", title: "Employee Hours", description: "View users total on site hours" },
    { id: 25, path: "/employees", title: "Employee average arrival and departure", description: "View users average arrival and departure times" },
    { id: 26, path: "/employees", title: "Employee average on site time", description: "View users average on site time" },
    { id: 27, path: "/employees", title: "Employee peak hours time", description: "View users peak hours on site" },
    { id: 28, path: "/employees", title: "Generate report", description: "Generate a report on employee statistics" },
    { id: 29, path: "/employees", title: "Search for employees", description: "View employee check-ins" },
    { id: 30, path: "/booking-statistics/bookings-dashboard", title: "Top 3 bookings", description: "View top 3 bookings in the system" },
    { id: 31, path: "/booking-statistics/bookings-dashboard", title: "Current bookings", description: "View current bookings in the system" },
    { id: 32, path: "/booking-statistics/bookings-dashboard", title: "Booking statistics", description: "View booking statistics" },
    { id: 33, path: "/booking-statistics/bookings-dashboard", title: "Booking history", description: "View historical data on bookings"},
    { id: 34, path: "/worker-dashboard", title: "most active workers", description: "View the most active workers in the system" },
    { id: 35, path: "/worker-dashboard", title: "least active workers", description: "View the least active workers in the system" },
    { id: 36, path: "/worker-dashboard", title: "peak hours", description: "View the peak hours of workers in the system" },
    { id: 37, path: "/worker-dashboard", title: "average on site time", description: "View the average on site time of workers in the system" },
    { id: 38, path: "/worker-dashboard", title: "average arrival and departure", description: "View the average arrival and departure times of workers in the system" },
    { id: 39, path: "/ai-dashboard", title: "office occupancy", description: "View the office occupancy in the system" },
    { id: 40, path: "/ai-dashboard", title: "available desks", description: "View the available desks in the system" },
    { id: 41, path: "/ai-dashboard", title: "bookings", description: "View the bookings in the system" },
    { id: 42, path: "/ai-dashboard", title: "check-ins today", description: "View the check-ins today in the system" },
    { id: 43, path: "/ai-dashboard", title: "predicted capacity levels", description: "View the predicted capacity levels in the system" },
    { id: 44, path: "/ai-dashboard", title: "get reccomendations", description: "Get reccomendations on which days to come into the office" },
    { id: 45, path: "/rooms", title: "add room", description: "Add a room to the system" },
    { id: 46, path: "/rooms", title: "edit room", description: "Edit a room in the system" },
    { id: 47, path: "/rooms", title: "delete room", description: "Delete a room in the system" },
    { id: 48, path: "/rooms", title: "view rooms", description: "View all rooms in the system" },
    { id: 49, path: "/rooms", title: "search rooms", description: "Search for a room in the system" },
    { id: 50, path: "/reports", title: "generate report", description: "Generate a report in the system" },
    { id: 51, path: "/reports", title: "download report", description: "Download a report in the system" },
    { id: 52, path: "/reports", title: "view report", description: "View a report in the system" },
    { id: 53, path: "/reports", title: "search report", description: "Search for a report in the system" },
    { id: 54, path: "/faq", title: "search faq", description: "Search for a faq in the system" },
    { id: 55, path: "/settings/profile", title: "update profile", description: "Update your profile in the system" },
    { id: 56, path: "/settings/profile", title: "change password", description: "Change your password in the system" },
    { id: 57, path: "/settings/profile", title: "update email", description: "Update your email in the system" },
    { id: 58, path: "/settings/profile", title: "update phone number", description: "Update your phone number in the system" },
    { id: 59, path: "/settings/profile", title: "update address", description: "Update your address in the system" },
    { id: 60, path: "/settings/profile", title: "update name", description: "Update your name in the system" },
    { id: 61, path: "/settings/profile", title: "update profile picture", description: "Update your profile picture in the system" },
    { id: 62, path: "/settings/appearance", title: "update theme", description: "Update your theme in the system" },
    { id: 63, path: "/rooms", title: "change room image", description: "Change the image of a room in the system" },
    { id: 64, path: "/user-locations", title: "add location", description: "Add a location to the system" },
    { id: 65, path: "/user-locations", title: "edit location", description: "Edit a location in the system" },
    { id: 66, path: "/user-locations", title: "delete location", description: "Delete a location in the system" },
    { id: 67, path: "/user-locations", title: "blacklist", description: "Blacklist a location in the system" },
    { id: 68, path: "/user-locations", title: "whitelist", description: "Whitelist a location in the system" },
    //{ id: 69, path: "/user-locations", title: "Google maps", description: "View the location on google maps and locate a specific place" },
    { id: 69, path: "/faq", title: "search faq", description: "Search for a faq in the system" },
    { id: 70, path: "/settings/notifications", title: "update notifications", description: "Update your notifications in the system" },
    { id: 71, path: "/settings/security", title: "update security", description: "Update your security in the system" },
    { id: 72, path: "/settings/about", title: "view about", description: "View the about page in the system" },
    { id: 73, path: "/settings/about", title: "view privacy policy", description: "View the privacy policy in the system" },
    { id: 74, path: "/settings/about", title: "view TOS", description: "View the TOS in the system" },
    { id: 75, path: "/settings/about", title: "view user manual", description: "View the user manual in the system" },
    { id: 76, path: "/booking-statistics", title: "generate report", description: "Generate a report in the system" },
    { id: 77, path: "/booking-statistics", title: "download report", description: "Download a report in the system" },
    { id: 78, path: "/booking-statistics", title: "view report", description: "View a report in the system" },
    { id: 79, path: "/booking-statistics", title: "search report", description: "Search for a report in the system" },
    { id: 80, path: "/worker-dashboard", title: "generate report", description: "Generate a report in the system" },
    { id: 81, path: "/worker-dashboard", title: "download report", description: "Download a report in the system" },
    { id: 82, path: "/worker-dashboard", title: "view report", description: "View a report in the system" },
    { id: 83, path: "/worker-dashboard", title: "search report", description: "Search for a report in the system" },
    { id: 84, path: "/employees", title: "generate report", description: "Generate a report in the system" },
    { id: 85, path: "/employees", title: "download report", description: "Download a report in the system" },
  ];