export const pages = [
    { id: 1, path: "/", title: "Dashboard Overview", description: "View the overview of the system info at a glance" },
    { id: 2, path: "/employees", title: "Dashboard Employees", description: "View employee details" },
    { id: 4, path: "/ai-dashboard", title: "AI Dashboard", description: "Leverage the power of AI to analyze office trends (office occupancy, available desks, reservations, check-ins today)" },
    { id: 5, path: "/rooms", title: "Rooms", description: "Update and edit available rooms in the building" },
    { id: 6, path: "/reports", title: "Reports", description: "Generate and download reports for analysis" },
    { id: 7, path: "/faq", title: "FAQ", description: "Get help on app usage" },
    { id: 8, path: "/settings/profile", title: "Profile", description: "Update your profile information" },
    { id: 9, path: "/settings/appearance", title: "Appearance", description: "Change the appearance of the app" },
    { id: 10, path: "/settings/notifications", title: "Notifications", description: "Manage your notification settings" },
    { id: 11, path: "/settings/security", title: "Security", description: "Manage your security settings" },
    { id: 12, path: "/settings/about", title: "About, Privacy Policy, TOS, User Manual", description: "View information about the app" },
    { id: 13, path: "/booking-statistics", title: "Booking Statistics", description: "View statistics on bookings" },
    { id: 14, path: "/worker-dashboard", title: "Worker Dashboard", description: "View organisation wide worker statistics" },
    { id: 15, path: "/employees", title: "Employees", description: "View employee details and employee statistics on an individualised level" },
    { id: 16, path: "/booking-statistics/overview", title: "Bookings Overview", description: "View overview statistics on bookings" },
    { id: 17, path: "/booking-statistics/bookings-dashboard", title: "Bookings Dashboard", description: "View deeper statistics on bookings" },
    { id: 18, path: "/user-locations", title: "User login locations", description: "Manage users allowed login locations, see their ip addresses for these allowed locations"},
    { id: 19, path: "/", title: "At a glance", description: "View the overview of the system info at a glance" },
    { id: 20, path: "/employees", title: "Admin", description: "Change admin status of employees" },
    { id: 21, path: "/employees", title: "Employee Statistics", description: "View employee statistics" },
    { id: 22, path: "/employees", title: "Site status", description: "View employee on site and offsite status" },
    { id: 23, path: "/employees", title: "Mail employee", description: "Send a personalised email to your employee" },
    { id: 24, path: "/employees", title: "Employee Hours", description: "View users total on site hours" },
    { id: 25, path: "/employees", title: "Employee average arrival and departure", description: "View users average arrival and departure times" },
    { id: 26, path: "/employees", title: "Employee average on site time", description: "View users average on site time" },
    { id: 27, path: "/employees", title: "Employee peak hours time", description: "View users peak hours on site" },
    { id: 28, path: "/employees", title: "Generate report", description: "Generate a report on employee statistics" },
    { id: 29, path: "/employees", title: "Search for employees", description: "View employee check-ins" },
    { id: 30, path: "/booking-statistics/bookings-dashboard", title: "Top 3 bookings", description: "View top 3 bookings in the system" },
    { id: 31, path: "/booking-statistics/bookings-dashboard", title: "Current bookings", description: "View current bookings in the system" },
    { id: 32, path: "/booking-statistics/bookings-dashboard", title: "Booking statistics", description: "View booking statistics" },
    { id: 33, path: "/booking-statistics/bookings-dashboard", title: "Booking history", description: "View historical data on bookings"}
  ];