services:
  occupi-backend-prod:
    image: $DOCKER_USERNAME/occupi-backend:latest
    container_name: occupi-backend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .prod.env
    environment:
      - ENV=production
    networks:
      - webnet
    ports:
      - "8080:8080"
    volumes:
      - /etc/letsencrypt/live/occupi.tech/fullchain.pem:/etc/letsencrypt/live/occupi.tech/fullchain.pem:ro
      - /etc/letsencrypt/live/occupi.tech/privkey.pem:/etc/letsencrypt/live/occupi.tech/privkey.pem:ro

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/occupi.tech/fullchain.pem:/etc/letsencrypt/live/occupi.tech/fullchain.pem:ro
      - /etc/letsencrypt/live/occupi.tech/privkey.pem:/etc/letsencrypt/live/occupi.tech/privkey.pem:ro
    depends_on:
      - occupi-backend-dev

networks:
  webnet:
    external: true
