services:
  rabbitmq-dev-local-local:
    image: rabbitmq:latest
    container_name: rabbitmq-dev-local-local
    ports:
      - "5674:5672"
    restart: on-failure:5
    volumes:
      - rabbitmq-dev-local-local:/var/lib/rabbitmq

  centrifugo-dev-local-local:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo-dev-local-local
    volumes:
      - ./configs/config.json:/centrifugo/config.json
      - centrifugo-dev-local-local:/centrifugo/data
    command: centrifugo -c config.json
    ports:
      - 8001:8000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  go-redis-dev-local-local:
    image: redis:latest
    container_name: go-redis-dev-local-local
    ports:
      - "11001:6379"
    restart: on-failure:5
    environment:
      REDIS_USERNAME: 
      REDIS_PASSWORD: 
    volumes:
      - redis-dev-local-local:/data

volumes:
  rabbitmq-dev-local-local:
  centrifugo-dev-local-local:
  redis-dev-local-local: