services:
  occupi-backend-prod:
    image: $DOCKER_USERNAME/occupi-backend:latest
    container_name: occupi-backend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      - ENV=production
    networks:
      - webnet
    ports:
      - "8080:8080"
    volumes:
      - /etc/letsencrypt/live/occupi.tech/fullchain.pem:/etc/letsencrypt/live/occupi.tech/fullchain.pem:ro
      - /etc/letsencrypt/live/occupi.tech/privkey.pem:/etc/letsencrypt/live/occupi.tech/privkey.pem:ro
    restart: on-failure:5
    depends_on:
      - mongo-prod
      - rabbitmq-prod

  mongo-prod:
    image: mongo:latest
    container_name: mongo-prod
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27017:27017"
    restart: on-failure:5
    volumes:
      - mongo-prod:/data/db
    command: ["mongod", "--bind_ip_all", "--port", "27017"]
    networks:
      - webnet

  rabbitmq-prod:
    image: rabbitmq:latest
    container_name: rabbitmq-prod
    ports:
      - "5672:5672"
    restart: on-failure:5
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    volumes:
      - rabbitmq-prod:/var/lib/rabbitmq
    networks:
      - webnet

volumes:
  mongo-prod:
  rabbitmq-prod:

networks:
  webnet:
    external: true
