services:
  occupi-backend-local:
      image: occupi-backend-local:latest
      container_name: occupi-backend-local
      build:
        context: .
        dockerfile: Dockerfile.local
      environment:
        - ENV=development
      ports:
        - "8081:8081"
      restart: on-failure:5
      depends_on:
        centrifugo-dev-local:
          condition: service_healthy
        rabbitmq-dev-local:
          condition: service_healthy

  rabbitmq-dev-local:
    image: rabbitmq:latest
    container_name: rabbitmq-dev-local
    ports:
      - "5673:5672"
    restart: on-failure:5
    volumes:
      - rabbitmq-dev-local:/var/lib/rabbitmq
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 3

  # centrifugo-dev-local:
  #   image: centrifugo/centrifugo:v5
  #   container_name: centrifugo-dev-local
  #   volumes:
  #     - ./configs/config.json:/centrifugo/config.json
  #     - centrifugo-dev-local:/centrifugo/data
  #   command: centrifugo -c config.json --health
  #   ports:
  #     - 8001:8000
  #   ulimits:
  #     nofile:
  #       soft: 262144
  #       hard: 262144
  #   healthcheck:
  #     test: curl -f http://localhost:8001/health
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5    

volumes:
  rabbitmq-dev-local:
  # centrifugo-dev-local:
