services:
  occupi-backend-prod:
    build: .
    container_name: occupi-backend-prod
    env_file:
      - .prod.env
    environment:
      - ENV=production
    networks:
      - webnet
    ports:
      - "8080:8080"

networks:
  webnet:
    external: true
