services:
  occupi-backend-dev:
    image: $DOCKER_USERNAME/occupi-backend:latest-develop
    container_name: occupi-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENV=development
    networks:
      - webnet
    ports:
      - "8081:8081"
    volumes:
      - /etc/letsencrypt/live/dev.occupi.tech/fullchain.pem:/etc/letsencrypt/live/dev.occupi.tech/fullchain.pem:ro
      - /etc/letsencrypt/live/dev.occupi.tech/privkey.pem:/etc/letsencrypt/live/dev.occupi.tech/privkey.pem:ro
    restart: on-failure:5
    depends_on:
      - mongo-dev
      - rabbitmq-dev

  mongo-dev:
    image: mongo:latest
    container_name: mongo-dev
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_INITDB_ROOT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_INITDB_ROOT_PASSWORD
    ports:
      - "27018:27017"
    restart: on-failure:5
    volumes:
      - mongo-dev:/data/db
    command: ["mongod", "--bind_ip_all", "--port", "27018"]
    networks:
      - webnet

  rabbitmq-dev:
    image: rabbitmq:latest
    container_name: rabbitmq-dev
    ports:
      - "5673:5672"
    restart: on-failure:5
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    volumes:
      - rabbitmq-dev:/var/lib/rabbitmq
    networks:
      - webnet

volumes:
  mongo-dev:
  rabbitmq-dev:

networks:
  webnet:
    external: true
