services:
  occupi-backend-prod:
    image: $DOCKER_USERNAME/occupi-backend:latest
    container_name: occupi-backend-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .prod.env
    environment:
      - ENV=production
    networks:
      - webnet
    ports:
      - "8080:8080"

networks:
  webnet:
    external: true
