services:
  occupi-backend-dev:
    image: $DOCKER_USERNAME/occupi-backend:latest-develop
    container_name: occupi-backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    environment:
      - ENV=development
    networks:
      - webnet
    ports:
      - "8081:8081"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - /etc/letsencrypt/live/dev.occupi.tech/fullchain.pem:/etc/letsencrypt/live/dev.occupi.tech/fullchain.pem:ro
      - /etc/letsencrypt/live/dev.occupi.tech/privkey.pem:/etc/letsencrypt/live/dev.occupi.tech/privkey.pem:ro
    restart: on-failure:5
    depends_on:
        rabbitmq-dev:
          condition: service_healthy
        centrifugo-dev:
          condition: service_started
        prometheus-dev:
          condition: service_started
        grafana-dev:
          condition: service_started
      
  rabbitmq-dev:
    image: rabbitmq:latest
    container_name: rabbitmq-dev
    ports:
      - "5673:5672"
    restart: on-failure:5
    environment:
      RABBITMQ_DEFAULT_USER: $RABBITMQ_DEFAULT_USER
      RABBITMQ_DEFAULT_PASS: $RABBITMQ_DEFAULT_PASS
    volumes:
      - rabbitmq-dev:/var/lib/rabbitmq
    networks:
      - webnet
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      interval: 30s
      timeout: 30s
      retries: 3

  centrifugo-dev:
    image: centrifugo/centrifugo:v5
    container_name: centrifugo-dev
    volumes:
      - ./centrifugo.config.json:/centrifugo/centrifugo.config.json
      - centrifugo-dev:/centrifugo/data
    command: centrifugo -c centrifugo.config.json
    ports:
      - 8001:8000
    ulimits:
      nofile:
        soft: 262144
        hard: 262144

  prometheus-dev:
    container_name: prometheus-dev
    image: prom/prometheus
    restart: on-failure:5
    extra_hosts:
      - host.docker.internal:host-gateway
    command:
      - --config.file=/etc/prometheus/prometheus.dev.yml
    volumes:
      - ./prometheus.dev.yml:/etc/prometheus/prometheus.dev.yml
    ports:
      - "9091:9090"

  grafana-dev:
    container_name: grafana-dev
    image: grafana/grafana
    restart: on-failure:5
    ports:
      - "10001:3000"

volumes:
  rabbitmq-dev:
  centrifugo-dev:

networks:
  webnet:
    external: true
