services:
  occupi-backend-dev:
    build: .
    container_name: occupi-backend-dev
    env_file:
      - .dev.env
    environment:
      - ENV=development
    networks:
      - webnet
    ports:
      - "8081:8081"

networks:
  webnet:
    external: true
