services:
  model:
    image: $DOCKER_USERNAME/model:latest
    container_name: model
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - webnet
    restart: on-failure:5
    depends_on:
      - tensorflow-serving

  tensorflow-serving:
    image: tensorflow/serving:latest
    ports:
      - "8501:8501"
    environment:
      MODEL_NAME: attendance_model
    volumes:
      - /home/$VM_USERNAME/model/attendance_model:/models/attendance_model
    command: >
      sh -c 'tensorflow_model_server --port=8501 --model_name=${MODEL_NAME} --model_base_path=/models/${MODEL_NAME}'

networks:
  webnet:
    external: true