name: Deploy Models 🤖🧠

on:
    push:
        branches: ["develop"]
        paths: [
            "models/**",
            ".github/workflows/deploy-models.yml"
        ]

    workflow_dispatch:

defaults:
    run:
        working-directory: models

jobs:
    deploy:
          name: 🛳️ Deploy Models 🤖🧠
          runs-on: ubuntu-latest
  
          steps:
              - name: ⬇️ Checkout code
                uses: actions/checkout@v4
  
              - name: 🪷 Copy files to VM
                uses: appleboy/scp-action@v0.1.5
                with:
                    host: ${{ secrets.VM_IP }}
                    username: ${{ secrets.VM_USERNAME }}
                    key: ${{ secrets.VM_SSH_KEY }}
                    source: "models/attendance_model,models/docker-compose.yml"
                    target: "/home/${{ secrets.VM_USERNAME }}/model"
  
              # SSH to VM and run commands
              - name: 🚀 SSH to VM
                uses: appleboy/ssh-action@master
                with:
                    host: ${{ secrets.VM_IP }}
                    username: ${{ secrets.VM_USERNAME }}
                    key: ${{ secrets.VM_SSH_KEY }}
                    script: |
                        cd /home/${{ secrets.VM_USERNAME }}/model/models
                        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
                        docker compose -f docker-compose.yml down
                        docker compose -f docker-compose.yml pull
                        docker compose -f docker-compose.yml up -d
