name: Test and Build golang

on:
  push:
    branches: ["not-yet-specified"]

  workflow_dispatch:

defaults:
  run:
    working-directory: occupi-backend

jobs:
  # test job
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/checkout@v4

      - name: Test
        run: go test ./tests/... 

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Golang
        uses: actions/checkout@v4

      - name: Build
        run: go build cmd/occupi-backend/main.go