services:
  attendance_model:
    image: tensorflow/serving:latest
    container_name: attendance_model
    ports:
      - "8501:8501"
    environment:
      MODEL_NAME: attendance_model
    volumes:
      - /attendance_model:/models/attendance_model
    command: >
      sh -c 'tensorflow_model_server --port=8501 --model_name=attendance_model --model_base_path=/models/attendance_model'
    networks:
      - webnet
    restart: on-failure:5

networks:
  webnet:
    external: true